// YouTube-client/src/app/youtube/components/video-metrics/video-metrics.component.ts
import { Component, Input } from '@angular/core';

import { Item } from 'src/app/core/models/youtube-api.model';

@Component({
  selector: 'youtube__video-metrics',
  templateUrl: './video-metrics.component.html',
  styleUrls: ['./video-metrics.component.scss'],
})
export class VideoMetricsComponent {
  @Input() public item!: Item;
}

<ul class="video-item__metrics" *ngIf="item.statistics">
  <li data-tooltip="Views">
    <div class="metrics__icon"></div>
    <p class="metrics__count">{{ item.statistics.viewCount | videoMetricsFormat }}</p>
  </li>
  <li data-tooltip="Likes">
    <div class="metrics__icon"></div>
    <p class="metrics__count">{{ item.statistics.likeCount | videoMetricsFormat }}</p>
  </li>
  <li data-tooltip="Favorites">
    <div class="metrics__icon"></div>
    <p class="metrics__count">{{ item.statistics.favoriteCount | videoMetricsFormat }}</p>
  </li>
  <li data-tooltip="Comments">
    <div class="metrics__icon"></div>
    <p class="metrics__count">{{ item.statistics.commentCount | videoMetricsFormat }}</p>
  </li>
</ul>

// YouTube-client/src/components/VideoMetrics/VideoMetrics.tsx
import { IPropsVideoMetricsComponent } from '../../models/app.models';
import MetricComponent from './Metric/Metric';
import styles from './VideoMetrics.module.scss';

export default function VideoMetricsComponent({ data }: IPropsVideoMetricsComponent) {
  const metrics = [
    {
      class: 'logo-views',
      count: data.viewCount,
      title: 'Views',
    },
    {
      class: 'logo-likes',
      count: data.likeCount,
      title: 'Likes',
    },
    {
      class: 'logo-comments',
      count: data.commentCount,
      title: 'Comments',
    },
    {
      class: 'logo-favorites',
      count: data.favoriteCount,
      title: 'Favorites',
    },
  ];

  return (
    <ul className={styles['video-metrics']}>
      {metrics.map((item) => (
        <li key={item.title}>
          <MetricComponent data={item} />
        </li>
      ))}
    </ul>
  );
}
