// YouTube-client/src/app/youtube/components/video-item/video-item.component.ts
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';

import { Item } from 'src/app/core/models/youtube-api.model';

@Component({
  selector: 'youtube__video-item',
  templateUrl: './video-item.component.html',
  styleUrls: ['./video-item.component.scss'],
})
export class VideoItemComponent {
  @Input() public item!: Item;

  constructor(private router: Router) {}

  detailed(): void {
    this.router.navigate([`main/detailed/${this.item.id}`]);
  }
}

<img class="video-item__img" [src]="item | videoImageThumbnail" [alt]="item.snippet.title" />
<youtube__video-metrics [item]="item"></youtube__video-metrics>
<p class="video-item__video-title title">{{ item.snippet.title }}</p>
<button class="video-item__button button" (click)="detailed()">more...</button>

// YouTube-client/src/components/VideoItem/VideoItem.tsx
import { useNavigate } from 'react-router';

import { IPropsVideoItemComponent } from '../../models/app.models';
import getVideoImageThumbnail from '../../utils/getVideoImageThumbnail';
import VideoMetricsComponent from '../VideoMetrics/VideoMetrics';
import styles from './VideoItem.module.scss';

export default function VideoItemComponent({ data }: IPropsVideoItemComponent) {
  const navigate = useNavigate();

  function selectVideo() {
    navigate(`/videos/${data.id}`);
  }

  return (
    <div className={styles['video-item']}>
      <img className={styles['video-item-img']} src={getVideoImageThumbnail(data)} alt={data.snippet.title} />
      <VideoMetricsComponent data={data.statistics} />
      <h3 className={`title ${styles['video-item-title']}`}>{data.snippet.title}</h3>
      <button className={`button ${styles['video-item-button']}`} type="button" onClick={selectVideo}>
        more...
      </button>
    </div>
  );
}
